services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: